#!/usr/bin/env bash
# Just changed to txt to see if that was causing issues with reading the file when using key-mappings only
# I tend to default to Markdown Syntax but this script displays a menu of urls that
# keep in a markdown doc. Then it opens that url with the browser I'm using that that time

set -eo pipefail
while true;
do
    file="$HOME/Gits/xfafniros/resources/bookmarks.txt"
    bkmk="$(bat $file | fzf --prompt="Open : " --border --margin=5% --color=dark --height=100% --reverse --header=" BOOKMARKS " --header-first)"
    if [[ $bkmk ]]
    then
        #flatpak run io.gitlab.librewolf-community "$bkmk"
        devour flatpak run io.gitlab.librewolf-community "$bkmk"
    else
        exit 1
    fi
done
sleep 1
exit
