#!/bin/bash
# Basic terminal run launcher 
set -eo pipefail
# May need to hard-code user in
dir1="$HOME/.local/bin"
dir2="/usr/bin"
dir3="/usr/games"

while true;
do
    Menu="$(exa $dir1 $dir2 $dir3 | uniq -u | fzf --prompt="Search for Program to Run : " --border=rounded --margin=5% --color=dark --height 100% --reverse --header="                    PROGRAMS " --info=hidden --header-first)" 

    exec devour "$Menu"
done
sleep 1
exit
