#!/usr/bin/env bash
set -eo pipefail
gits_dir=$HOME"/Gits"
if [ -d "$gits_dir" ] ; then
    echo "Directory %s found in Path" 
    pushd $gits_dir
    diff_gits="$(exa $gits_dir | fzf --prompt="Open : " --border --margin=5% --color=dark --height=100% --reverse --header=" BOOKMARKS " --header-first)"
    if [[ $diff_gits ]]
    then
        cd $gits_dir"/"$diff_gits && echo $diff_gits && git remote update && git status -uno
    else
        exit
    fi
    popd
else
    echo "Directory ~/Gits is not found in Path"
fi
