#!/usr/bin/env bash
set -eo pipefail
while true;
do
    gits_dir=$HOME"/Gits"
    if [ -d "$gits_dir" ] ; then
        echo "Directory %s found in Path" 
        pushd $gits_dir
        diff_gits="$(exa $gits_dir | fzf --prompt="Check : " --border --margin=5% --color=dark --height=100% --reverse --header=" CHECK GITS " --header-first)"
        if [[ $diff_gits ]]
        then
            cd $gits_dir"/"$diff_gits && echo $diff_gits && git remote update && git status -uno
        else
            popd
            exit 1
        fi
        popd
        exit 1
    else
        echo "Directory ~/Gits is not found in Path"
        popd
        exit 1
    fi
done
popd
sleep 1
exit
