#!/usr/bin/env bash
set -eo pipefail
#pushd ~/Gits/"$1"
#git pull --no-rebase
#popd

gits_dir=$HOME"/Gits"
if [ -d "$gits_dir" ] ; then
    echo "Directory %s found in Path" 
    pushd $gits_dir
    diff_gits=($(ls -d */))
    for i in "${diff_gits[@]}"; do
        cd $gits_dir"/"$i && echo $i && git pull --no-rebase
    done
    popd
else
    echo "Directory ~/Gits is not found in Path"
fi
