#!/usr/bin/env bash
# Simple encrypt program

selection="$(exa -a | fzf --height 95% --reverse --info hidden --prompt "ENCRYPT FILE: "  --header-first --preview ' cd_pre="$(echo $(pwd)/$(echo {}))";
                    echo $cd_pre;
                    echo;
                    exa -a --color=always "${cd_pre}";
                    termpix --width 100 --true-color {} 2>/dev/null;
                    bat --style=numbers --theme=ansi --color=always {} 2>/dev/null' --bind alt-j:preview-down,alt-k:preview-up --preview-window=right:65%)"

if [[ $selection ]]
then
    printf "Output File: \n"
    read -r output_file
    if [[ $output_file ]]
    then
        printf "Decrypting %s.\n" "$selection"
        gpg --output $output_file --decrypt $selection
        read -p "Would you like to Delete Original Encrypted File?:(Y/n) " -n 1 -r
        if [[ $REPLY =~ ^[Yy]$ ]]; then
                rm -i $selection
            elif [[ $REPLY =~ ^[Nn]$ ]]; then
                printf "\nNot Deleting Original Encrypted File\n"
            fi
    else
        printf "Error either in Selection, or Output File!\n"
    fi
else
    printf "No Selection input!\n"
fi
