#!/usr/bin/env bash
# Simple encrypt program

selection="$(exa -a | fzf --height 95% --reverse --info hidden --prompt "ENCRYPT FILE: "  --header-first --preview ' cd_pre="$(echo $(pwd)/$(echo {}))";
                    echo $cd_pre;
                    echo;
                    exa -a --color=always "${cd_pre}";
                    termpix --width 100 --true-color {} 2>/dev/null;
                    bat --style=numbers --theme=ansi --color=always {} 2>/dev/null' --bind alt-j:preview-down,alt-k:preview-up --preview-window=right:65%)"

if [[ $selection ]]
then
    printf "Signing %s.\n" "$selection"
    gpg --sign $selection
    else
        printf "Likely Error either in Selection!\n"
        exit 1
    fi
else
    printf "No Selection Input!\n"
    exit 1
fi
sleep 1
exit
